% pop_eventrange() - pop up a graphic interface to select event range. This
%                    function save several variables in root : 
%                 1) a variable called "eventli1" which
%                    contains the chosen event of the first listbox of the
%                    pop-up window;
%                 2) a variable called "eventli2" which
%                    contains the chosen event of the second listbox of the
%                    pop-up window;
%                 3) a variable called "eventl" which
%                    contains the string composed of the two chosen event of the
%                    pop-up window separated by a space;
%                 To recover these variables, you have to write :
%                       name = getappdata(0,'name_of_the_variable');
%
% Author: Fanny Grosselin, 2018
%
% Usage:
%   >> pop_eventrange(eventtype);
%
% Input:
%   eventtype     - input list of events you want to display in
%                   listboxes of the pop-up window.

function pop_eventrange(eventtype)
    
    if nargin < 1
        help pop_eventrange;
        return;
    end;
    if isempty(eventtype), disp('Empty input'); return; end;
    
    % list of events
    % --------------
    event1 = {};
    for j = 1:length(eventtype)
        event1{end+1} = [eventtype(j)];
    end;
    event1{end+1} = sprintf('%s','END_OF_SIGNAL');
    eventf = [event1{1,:}]; 
    setappdata(0,'eventf',eventf);
    
    % Callback
    % --------
    okevent = [...
        'eventf = getappdata(0,''eventf'');'...
        'eventlist1 = get(findobj(''parent'', gcbf, ''tag'', ''firstevent''),''value'');'...
        'if eventlist1(1) == length(eventf)'...
            '    eventlist1 = sprintf(''%s'',''END_OF_SIGNAL'');'...
        'else'...
            '    eventlist1 = truelist{eventlist1};'...
        'end;'...
        'setappdata(0,''eventli1'',eventlist1);'...
        'eventlist2 = get(findobj(''parent'', gcbf, ''tag'', ''secondevent''),''value'');'...
        'if eventlist2 == length(eventf)'...
            '    eventlist2 = sprintf(''%s'',''END_OF_SIGNAL'');'...
            '    eventlist = sprintf(''%s %s'',eventlist1, eventlist2);'...
        'else'...
            '    eventlist2 = truelist{eventlist2};'...
            '    eventlist = sprintf(''%s %s'',eventlist1, eventlist2);'...
        'end;'...
        'setappdata(0,''eventli2'',eventlist2);'...
        'recupevent = getappdata(0,''eventl'');'...
        'set(recupevent,''string'',eventlist);'...
        'close(gcbf);'...
        'clear eventlist tmpevent recupevent eventl truelist eventlist1 eventlist2 eventf;'];
    
    
    % GUI 
    % ---
    supergui ('geomhoriz', {[1] [1] [1] [1] [1] [1] [1 1 1]}, 'geomvert', [1 4 1 1 4 1 1], 'uilist', { ...
    { 'style', 'text', 'string','Choose the first condition of the event range', 'fontweight','bold'}...
    { 'style', 'listbox','string',eventf , 'value', 1 ,'max', 1, 'tag', 'firstevent' }...
    {}...
    { 'style', 'text','string', 'Choose the second condition for the event range', 'fontweight','bold'}...
    { 'style', 'listbox', 'string',eventf , 'value', 1, 'max', 1, 'tag', 'secondevent'}...
    {}...
    { 'style', 'pushbutton' , 'string', 'Help' 'callback' 'pophelp(''pop_eventrange'');' }...
    { 'style', 'pushbutton' , 'string', 'Cancel' 'callback' 'close(gcbf);' } ...
    { 'style', 'pushbutton' , 'string', 'OK','callback', okevent}},...
    'title', 'Choose event range -- pop_eventrange()');
    
    
    
return;
